name: frontend test
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  frontend_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Set node version 22
      uses: actions/setup-node@v2
      with:
        node-version: '22.1.0'
    - name: Install packages
      run: npm ci
    - name: Test regression
      run: npm test
