name: frontend test
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  frontend_test:
    # using: 'node16'
    runs-on: ubuntu-latest

    steps:
    - name: 1. checkout repo
      uses: actions/checkout@v4
    - name: 2. set node version 22
      uses: actions/setup-node@v2
      with:
        node-version: '22.x'
    - name: 3. install npm packages
      run: npm ci
    - name: 4. run tests
      run: npm test
