name: frontend_test
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  vitest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Set node version 22
      uses: actions/setup-node@v2
      with:
        node-version: '22.1.0'
        cache: 'npm'
    - name: Test regression
      run: |
        npm ci
        npm run tada_doctor
        npm run tada_check
        npm test
        git diff --name-status --exit-code .
